apiVersion: v1
kind: ConfigMap
metadata:
  name: streamx-config
  namespace: streamx
data:
  SPRING_PROFILES_ACTIVE: prod
  JWT_SECRET: "9a6f8b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a"
  POSTGRES_USER: "streamx"
  POSTGRES_HOST: "streamx-postgres"
  POSTGRES_PORT: "5432"

---
apiVersion: v1
kind: Secret
metadata:
  name: streamx-secret
  namespace: streamx
type: Opaque
stringData:
  POSTGRES_PASSWORD: "streamx_password"
