import React, { useCallback, useEffect, useState } from 'react';
import { Plus, RefreshCw, Tag } from 'lucide-react';
import { adminService, audit } from '../services/adminService';
import { errorMessage } from '../api/client';
import type { Genre } from '../types';
import { EmptyState, ErrorBanner, LoadingState, SuccessBanner } from '../components/common/Feedback';

const byName = (a: Genre, b: Genre) => a.name.localeCompare(b.name);

export const GenresPage: React.FC = () => {
  const [genres, setGenres] = useState<Genre[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [name, setName] = useState('');
  const [creating, setCreating] = useState(false);
  const [createError, setCreateError] = useState<string | null>(null);
  const [success, setSuccess] = useState<string | null>(null);

  const load = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const list = await adminService.getGenres();
      setGenres([...list].sort(byName));
    } catch (err) {
      setError(errorMessage(err, 'Failed to load genres'));
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    load();
  }, [load]);

  const handleCreate = async (e: React.FormEvent) => {
    e.preventDefault();
    const trimmed = name.trim();
    if (!trimmed) return;
    setCreating(true);
    setCreateError(null);
    setSuccess(null);
    try {
      const created = await adminService.createGenre(trimmed);
      setGenres((list) => [...list.filter((g) => g.id !== created.id), created].sort(byName));
      audit({ action: 'GENRE_CREATED', targetType: 'GENRE', targetId: created.id, details: created.name });
      setSuccess(`Genre "${created.name}" created (slug: ${created.slug}).`);
      setName('');
    } catch (err) {
      setCreateError(errorMessage(err, 'Failed to create genre'));
    } finally {
      setCreating(false);
    }
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between border-b border-slate-800 pb-4">
        <div>
          <h3 className="text-lg font-bold text-white">Genre Taxonomy</h3>
          <p className="text-xs text-slate-400">
            Genres used to classify movies and TV shows. Genres cannot be renamed or deleted from the admin API.
          </p>
        </div>
        <button
          onClick={load}
          disabled={loading}
          className="flex items-center gap-2 px-3 py-2 bg-slate-900 border border-slate-800 hover:bg-slate-800 text-slate-300 rounded-lg text-xs font-semibold transition disabled:opacity-50"
        >
          <RefreshCw className={`w-4 h-4 ${loading ? 'animate-spin' : ''}`} />
          Refresh
        </button>
      </div>

      <form onSubmit={handleCreate} className="bg-slate-900 border border-slate-800 rounded-xl p-5 space-y-3">
        <h4 className="text-xs font-bold text-slate-400 uppercase tracking-wider">Create Genre</h4>
        <div className="flex flex-col sm:flex-row gap-3">
          <input
            type="text"
            required
            maxLength={100}
            value={name}
            disabled={creating}
            onChange={(e) => setName(e.target.value)}
            placeholder="Genre name"
            className="flex-1 px-3.5 py-2 bg-slate-950 border border-slate-800 rounded-lg text-xs text-white placeholder-slate-500 focus:outline-none focus:border-red-500 disabled:opacity-50"
          />
          <button
            type="submit"
            disabled={creating || !name.trim()}
            className="flex items-center justify-center gap-2 px-4 py-2 bg-red-600 hover:bg-red-700 text-white rounded-lg text-xs font-semibold transition disabled:opacity-50"
          >
            <Plus className="w-4 h-4" />
            {creating ? 'Creating…' : 'Create Genre'}
          </button>
        </div>
        <p className="text-[11px] text-slate-500">The slug is generated by the server from the name.</p>
        <ErrorBanner message={createError} />
        <SuccessBanner message={success} />
      </form>

      {loading && genres.length === 0 ? (
        <LoadingState label="Loading genres…" />
      ) : error ? (
        <ErrorBanner message={error} onRetry={load} />
      ) : genres.length === 0 ? (
        <div className="bg-slate-900 border border-slate-800 rounded-xl">
          <EmptyState title="No genres yet" hint="Create the first genre above to start classifying catalog titles." />
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          {genres.map((g) => (
            <div key={g.id} className="bg-slate-900 border border-slate-800 rounded-xl p-5">
              <h4 className="font-bold text-white mb-1 flex items-center gap-2 text-sm">
                <Tag className="w-4 h-4 text-red-500" />
                {g.name}
              </h4>
              <p className="text-xs text-slate-400 font-mono">/{g.slug}</p>
              <p className="text-[10px] text-slate-600 font-mono mt-1 truncate">{g.id}</p>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};
